spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/batch
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true

  batch:
    job:
      names: ${job.name:jpaItemWriterJob}
    initialize-schema: always
logging:
  level:
    org.springframework.batch: DEBUG
